---
output: pdf_document
header-includes:
    - \usepackage{setspace}\setstretch{0.5}
    - \usepackage{multicol}
geometry: margin=0.8in
fontsize: 10pt
---

\sffamily

\pagestyle{empty}

\center \LARGE \textbf{Ngoc Minh Quang Nguyen}

\normalsize

`r fontawesome::fa("phone-alt")` +1 (937) 925-6791 \qquad
`r fontawesome::fa("envelope")` <nminhquang.99@gmail.com> \qquad
`r fontawesome::fa("link")` [qntkhvn.netlify.app](https://qntkhvn.netlify.app)

`r fontawesome::fa("linkedin")` [linkedin.com/in/mqnnguyen](https://www.linkedin.com/in/mqnnguyen) \qquad
`r fontawesome::fa("github")` [qntkhvn](https://github.com/qntkhvn) \qquad
`r fontawesome::fa("twitter")` [\@qntkhvn](https://twitter.com/qntkhvn) \qquad

<!-- ## Contact Information -->

<!-- -   Born: August 6, 1999, Nha Trang, Khanh Hoa, Vietnam -->

<!-- -   Nationality: Vietnamese -->

<!-- -   US Visa Status: F-1 (Full-time Academic Student) -->

\raggedright

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{EDUCATION}
\hrulefill
\normalsize
\vspace{\baselineskip}
    
\textbf{Loyola University Chicago} \hspace*{\fill} Chicago, IL

\textbf{Master of Science, Applied Statistics} \hspace*{\fill} August 2020 - December 2021 (Expected)
\begin{itemize}
\item Current GPA: 4.00/4.00 
\end{itemize}

\vspace{2mm}

\textbf{Wittenberg University} \hspace*{\fill} Springfield, OH

\textbf{Bachelor of Science, Mathematics and Data Science} \hspace*{\fill} August 2017 - May 2020
\begin{itemize}
\item Summa Cum Laude; GPA: 3.97/4.00
\item Departmental Honors in Mathematics
\item Phi Beta Kappa and Pi Mu Epsilon
\end{itemize}
    
<!-- ## Research Interests -->
<!-- \begin{itemize} -->
<!--     \item[] Sports Analytics; Data Visualization; R Packages; Mathematical Statistics. -->
<!-- \end{itemize} -->

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{RESEARCH INTERESTS}
\hrulefill
\normalsize

\begin{itemize} 
\onehalfspacing
\item[] Data science, supervised learning; statistical applications in sports; data visualization; reproducibility in data science; statistics and data science education; statistical consulting.
\end{itemize}

\setstretch{0.55}

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{RESEARCH EXPERIENCE}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{Loyola University Chicago} \hspace*{\fill} Chicago, IL

\textbf{Graduate Research Assistant} \hspace*{\fill} August 2020 - present

Advisor: Dr. Gregory J. Matthews

\begin{itemize} 
\item Project: Estimating the aging curves in baseball using multiple imputation with a hierarchical structure.
\item Project: Evaluating the concerns regarding the combined competition format and rank-product scoring in sport climbing through simulations and data analysis.
\item Project: Statistical models for inferring the gender of stickleback fossil. 
\end{itemize}

<!-- \textit{Estimating Aging Curves in Baseball using Multiple Imputation}. Advised by Dr. Gregory J. Matthews. -->

\vspace{2mm}

\textbf{Wittenberg University} \hspace*{\fill} Springfield, OH

\textbf{Senior Honors Thesis} \hspace*{\fill} August 2019 - May 2020

Advisor: Dr. Douglas M. Andrews

Title: Predictive Models of English Premier League Goal Scoring

\begin{itemize} 
\item Determined that the Poisson process provides a good fit for modeling the time and event properties of goal scoring in the English Premier League
\item Utilized Poisson regression to simulate and predict the outcomes for a Premier League season.
\end{itemize}

<!-- \begin{itemize}  -->
<!--     \item Wittenberg University, Department of Mathematics and Computer Science, Springfield, Ohio -->
<!--     \item[] Senior Honors Thesis Research \hspace*{\fill} August 2019 - May 2020 -->
<!--     \item[] \textit{Predictive Models of English Premier League Goal Scoring}. Advised by Dr. Douglas M. Andrews. -->
<!-- \end{itemize} -->

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{ACADEMIC EXPERIENCE}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{Loyola University Chicago, Department of Mathematics and Statistics} \hspace*{\fill} Chicago, IL

\textbf{Instructor} (Accepted Position) \hspace*{\fill} January 2022 - May 2022

\begin{itemize}

\item Appointed as a part-time instructor for Spring 2022 semester.

\item Courses: Fundamentals of Statistics (STAT 103, 2 sections)

\end{itemize}

\vspace{2mm}

\textbf{Wittenberg University} \hspace*{\fill} Springfield, OH

\textbf{Math Workshop Head Tutor} \hspace*{\fill} August 2018 - May 2020

\begin{itemize}

\item Tutored all levels of Mathematics and Statistics/Data Science; and introductory levels of Computer Science, Economics, and Chemistry.  Worked with students one-on-one as well as in small groups.

\item Coordinated annual GRE Quantitative training sessions. Created basic math skills assessment worksheets for introductory-level Statistics classes.

\item Performed daily updates on student activity tracking database. Analyzed time data and fixed bad time entries.

\item Assisted the director with the transition to remote tutoring and implementing new video conferencing platform.

\end{itemize}

\vspace{2mm}

\textbf{Faculty Aide (Teaching/Research Assistant)} \hspace*{\fill} August 2018 - May 2020

\begin{itemize}

\item Provided aid to Dr. Sunny Jeong with Business courses including International Business, Business Research Methods, Global Social Entrepreneurship, and Business Ethics and Leadership.

\item Updated course websites, created and graded online assignments, and compiled student grades.

\item Participated in professor’s research on finding new literature and resources. Developed new learning case studies and reading questions.    
    
\end{itemize}

\vspace{2mm}

\textbf{Clarkston Senior High School} \hspace*{\fill} Clarkston, MI

\textbf{S.U.M. (Student Understanding Math) Assistant} \hspace*{\fill} January 2017 - May 2017

\begin{itemize}

\item Facilitated daily Algebra II lessons and assisted students with in-class materials and homework assignments.

\end{itemize}

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{COMPUTING SKILLS}
\hrulefill
\normalsize
\vspace{\baselineskip}

-   Techniques: data visualization, data wrangling, data mining, machine learning, statistical inference, web scraping

-   Advanced knowledge: R/RStudio - `tidyverse` (`dplyr`, `ggplot2`), R Markdown

-   Basic knowledge: Python; Java; SQL; SAS; Git/GitHub; \LaTeX

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{PAPERS}
\hrulefill
\normalsize
\vspace{\baselineskip}

-   \textbf{Nguyen, Q.} (2021). "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{New England Journal of Statistics in Data Science} (To appear). [[arXiv:2105.09881]](https://arxiv.org/abs/2105.09881).

-   \textbf{Nguyen, Q.}, Butler, H., Matthews, G.J. (2021). "An Examination of Sport Climbing's Competition Format and Scoring System." (Pre-print). [[arXiv:2111.05310]](https://arxiv.org/abs/2111.05310).

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{PRESENTATIONS \& POSTERS}
\hrulefill
\normalsize
\vspace{\baselineskip}

-   Presentation. "An Examination of Sport Climbing's Competition Format and Scoring System" \textit{Reproducible Research Competition, Carnegie Mellon Sports Analytics Conference}, November 2021. \textbf{Open Methodology Track Winner}

-   Poster. "Concerns Regarding Sport Climbing Competition Format and Scoring System: Who's Suffering?" \textit{UConn Sports Analytics Conference}, October 2021. \textbf{Student Poster Award Winner}.

-   Presentation. "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{Graduate Research Symposium, Loyola University Chicago}, March 2021.

-   Presentation (pre-recorded). "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{Midwest Sports Analytics Meeting}, November 2020.

<!-- -   Presentation. "Poisson Modeling and Predicting English Premier League Goal Scoring." International Research Symposium, International Education Week, Loyola University Chicago, November 2020. -->

<!-- -   Presentation. "Poisson Modeling and Predicting English Premier League Goal Scoring." Ohio State Sports Analytics Conference, November 2020. -->

-   Poster. "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{NextGen: Data Science Day, New England Statistical Society}, November 2020. \textbf{Poster Competition Co-Winner, Undergrad/MS Group}.

-   Poster. "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{Carnegie Mellon Sports Analytics Conference}, October 2020.

-   Poster. "Poisson Modeling and Predicting English Premier League Goal Scoring." \textit{UConn Sports Analytics Conference}, October 2020.

<!-- -   Presentation (pre-recorded). "\textit{Something Fishy About Manchester United’s Distribution of Goals Scored.}" Department of Mathematics and Computer Science’s Colloquium Series, Wittenberg University, October 2020. -->

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{HONORS \& AWARDS}
\hrulefill
\normalsize
\vspace{\baselineskip}

\begin{itemize}

\item \textbf{Reproducible Research Competition Winner}, Open Methodology Track, Carnegie Mellon Sports Analytics Conference (CMSAC), 2021.

\item \textbf{Best Student Poster Award}, UConn Sports Analytics Symposium (UCSAS), 2021

\item \textbf{Poster Competition Co-Winner}, Undergrad/MS Group, New England Statistical Society (NESS) - NextGen: Data Science Day, 2020

\item \textbf{Merit Award}, MS in Applied Statistics Program, Loyola University Chicago, 2020-2021.

\item \textbf{Summa Cum Laude}. Graduated with the highest distinction, Wittenberg University, 2020.

\item \textbf{Departmental Honors in Mathematics}, Department of Mathematics and Computer Science, Wittenberg University, 2020.

\item \textbf{Phi Beta Kappa}, Omicron of Ohio Chapter, Wittenberg University, 2020.

\item \textbf{Pi Mu Epsilon}, Ohio Upsilon Chapter, Wittenberg University, 2020.

\item \textbf{The Charles and Elsie Little Mathematics Award}, Department of Mathematics and Computer Science, Wittenberg University, 2020
\begin{itemize}
\item Awarded to the most outstanding senior mathematics and data science majors.
\end{itemize}

\item \textbf{Pick and Pen}, Wittenberg University, 2019.
    
\item \textbf{Mathematics 202 Award}, Department of Mathematics and Computer Science, Wittenberg University, 2018.
\begin{itemize}
\item Awarded to an outstanding first-year student in the introductory calculus sequence.
\end{itemize}
    
\item \textbf{Textbook Award}, Department of Mathematics and Computer Science, Wittenberg University, 2018.
\begin{itemize}
\item Awarded to first-year students majoring in the Department of Mathematics and Computer Science.
\end{itemize}

\item \textbf{Phi Eta Sigma}, Wittenberg University, 2018.

\item \textbf{Dean's List}, Wittenberg University, Fall 2017 - Spring 2020 (all semesters).
    
\item \textbf{International Student Scholarship} and \textbf{International Student Grant Program}, Wittenberg University, 2017-2020

\end{itemize}
    
<!-- -   Other Honors -->

<!--     -   The Charles E. Chatfield Global Awareness Award Nominee, Wittenberg University, Spring 2020 -->

<!--     -   Homecoming Royalty Nominee, Wittenberg University, Fall 2019 -->

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{COURSEWORK}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{Graduate} \hspace*{\fill} Loyola University Chicago

\textbf{Statistics} (\* In progress) \hspace*{\fill} Current GPA: 4.00/4.00

\vspace{1mm}

\begin{multicols}{2}
\begin{itemize}
\item Predictive Analytics*
\item Statistical Computation and Simulation*
\item Statistical Consulting*
\item Statistical Design and Analysis of Experiments*
\item Advanced Statistical Inference (Independent Study)
\item Nonparametric Statistics 
\item Categorical Data Analysis
\item Probability \& Mathematical Statistics
\item Applied Regression Analysis 
\item SAS Programming \& Applied Statistics 
\end{itemize}
\end{multicols}

\textbf{Undergraduate} \hspace*{\fill} Wittenberg University

\textbf{Statistics/Data Science} \hspace*{\fill} Major GPA: 4.00/4.00

\vspace{1mm}

\begin{multicols}{2}
\begin{itemize}
\item Mathematical Statistics
\item Univariate Probability
\item Statistical Modeling
\item Introduction to Data Science with R
\item Computer Programming II with Java
\item Computer Programming I with Python
\item Databases
\item Introductory Statistics/Data Analysis
\end{itemize}
\end{multicols}

\textbf{Mathematics} \hspace*{\fill} Major GPA: 4.00/4.00

\vspace{1mm}

\begin{multicols}{2}
\begin{itemize}
\item Graph Theory
\item Real Analysis
\item Abstract Algebra
\item Linear Algebra
\item Multivariable Calculus
\item Differential Equations
\item Foundations of Geometry
\item Discrete Mathematics \& Proofs
\item Calculus II
\item Calculus I
\end{itemize}
\end{multicols}

\vspace{\baselineskip}
\large \textbf{MEDIA}
\hrulefill
\normalsize
\vspace{\baselineskip}

*   "Can you pick the AFL's Brownlow Medal winner without knowing the first thing about Australian rules?" \url{https://www.abc.net.au/news/2021-09-19/afl-trying-to-predict-the-2021-brownlow-medal-winner/100472246}

\vspace{2mm}

\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{DATA COMPETITIONS}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{2021 Humana-Mays Healthcare Analytics Case Competition} \hspace*{\fill} Texas A&M University, Mays Business School

\vspace{1mm}

Round 1 (Prediction Accuracy and Fairness) \hspace*{\fill} Place: 2/75 

\vspace{2mm}

\textbf{SLICED} \hspace*{\fill} Kaggle Competition 

\vspace{1mm}

Season 1, Episode 9 - 2021 \hspace*{\fill} Place: 1/23 (Audience participation) 

\vspace{1mm}

Season 1, Episode 10 - 2021 \hspace*{\fill} Place: 2/27 (Audience participation) 

\vspace{2mm}


\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{ACTIVITIES}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{Wittenberg University} \hspace*{\fill} Springfield, OH

\vspace{1mm}

International Orientation Assistant \hspace*{\fill} 2018 \& 2019

\vspace{2mm}

Witt Math Club, Secretary and Chair of Contest Recruitment \hspace*{\fill} 2018-2020

\vspace{1mm}

Trivia Night Host \hspace*{\fill} 2020

\vspace{1mm}

East Asian Studies Club \hspace*{\fill} 2019

\vspace{1mm}

American International Association \hspace*{\fill} 2017

\vspace{2mm}

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{COMMUNITY SERVICE}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{The Fuller Center for Housing} \hspace*{\fill} Americus/Albany, GA

Wittenberg University's Service Immersion Spring Break Trip \hspace*{\fill} 2019

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{LANGUAGES}
\hrulefill
\normalsize
\vspace{\baselineskip}

Bilingual: \textbf{Vietnamese} (native language) and \textbf{English} (proficient)

\vspace{\baselineskip}
\vspace{\baselineskip}
\vspace{\baselineskip}
\large \textbf{EXCHANGE PROGRAMS}
\hrulefill
\normalsize
\vspace{\baselineskip}

\textbf{Clarkston Senior High School} \hspace*{\fill} Clarkston, MI

Educatius Group, US F-1 Academic Exchange Program \hspace*{\fill} 2016-2017

\vspace{2mm}

\textbf{Lead Hill High School} \hspace*{\fill} Lead Hill, AR

Cultural Academic Student Exchange (CASE) \hspace*{\fill} 2015-2016

\vspace{5mm}